#!/bin/bash
set -e

CONFIG_FILE="/var/www/html/Include/Config.php"

# Resolve environment variables with fallback
DB_HOST="${DB_SERVER_NAME:-${MYSQL_DB_HOST:-database}}"
DB_PORT="${DB_SERVER_PORT:-${MYSQL_DB_PORT:-3306}}"
DB_USER_NAME="${DB_USER:-${MYSQL_USER:-churchcrm}}"
DB_PASS="${DB_PASSWORD:-${MYSQL_PASSWORD:-changeme}}"
DB_DATABASE="${DB_NAME:-${MYSQL_DATABASE:-churchcrm}}"
ROOT_PATH_VAL="${ROOT_PATH:-}"
APP_URL="${CRM_URL:-${APP_URL:-http://localhost/}}"

# Ensure CRM_URL ends with a trailing slash (required by ChurchCRM ConfigLoader)
if [ -n "$APP_URL" ]; then
    case "$APP_URL" in
        */) ;;
        *) APP_URL="${APP_URL}/" ;;
    esac
fi

# Ensure directories exist and have proper permissions
mkdir -p /var/www/html/Images/Person /var/www/html/Images/Family /var/www/html/logs

# Protect image directories if .htaccess is missing (GHSA-r286-h493-ppwj)
if [ ! -f /var/www/html/Images/Person/.htaccess ]; then
    echo "Require all denied" > /var/www/html/Images/Person/.htaccess
fi
if [ ! -f /var/www/html/Images/Family/.htaccess ]; then
    echo "Require all denied" > /var/www/html/Images/Family/.htaccess
fi

# Generate Include/Config.php if not present and database credentials are provided
if [ ! -f "$CONFIG_FILE" ]; then
    echo "[ChurchCRM Dokploy Entrypoint] Generating Config.php from environment variables..."
    cat <<EOF > "$CONFIG_FILE"
<?php
/*******************************************************************************
 *
 *  filename    : Include/Config.php
 *  website     : https://churchcrm.io
 *  description : global configuration generated by Dokploy entrypoint
 *
 ******************************************************************************/

\$sSERVERNAME = '${DB_HOST}';
\$dbPort = '${DB_PORT}';
\$sUSER = '${DB_USER_NAME}';
\$sPASSWORD = '${DB_PASS}';
\$sDATABASE = '${DB_DATABASE}';

\$sRootPath = '${ROOT_PATH_VAL}';
\$bLockURL = false;
\$URL[0] = '${APP_URL}';

error_reporting(E_ERROR);

require_once dirname(__FILE__).DIRECTORY_SEPARATOR.'LoadConfigs.php';
EOF
    echo "[ChurchCRM Dokploy Entrypoint] Config.php successfully generated."
fi

# Ensure Apache user owns the uploaded images, config, and logs
chown -R www-data:www-data /var/www/html/Images /var/www/html/Include /var/www/html/logs
chmod 640 "$CONFIG_FILE" 2>/dev/null || true

exec "$@"
